import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { SettingsStateProps } from "../../types/settings.types";
import { UserData } from "../../types/user.types";

const initialState: SettingsStateProps = {
  isDark: true,
  userData: {
    id: 0,
    first_name: "",
    last_name: "",
    username: "",
    email: "",
    phone_number: "",
    social_type: "",
    social_id: "",
    is_social: 0,
    email_verified_at: "",
    profile_image: "",
    otp: "",
    otp_expired_at: "",
    is_verified: 0,
    card_number: "",
    card_type: "",
    card_cvv: "",
    card_expiry: "",
    card_holder_name: "",
    is_card: 0,
    push_notification: 0,
    new_message: 0,
    new_items: 0,
    purchase_item: 0,
    created_at: "",
    updated_at: "",
    acc_verified: 0,
    iso: "",
    type: "",
    is_profile_completed: 0,
    step: 0,
    profile_percentage: 0,
    address: "",
    insurance_number: "",
    insurance_copies: "",
    address_proofs: "",
    license_number: "",
    license_copies: "",
    vehicle_type: "",
    city: "",
    rate: 0,
    avg_rate: 0,
    total_user_rate: 0,
    device_type: "",
    device_token: "",
    fcm_token: "",
    customer_id: "",
    latitude: "",
    longitude: "",
    is_blocked_by_admin: 0,
    online: 0,
    stripe_account_id: "",
    apple_secret: "",
    stripe_enabled: 0,
    house_images: "",
    street_address_1: "",
    street_address_2: "",
    country: "",
    zip_code: "",
    kyc_documents: "",
    id_type: null,
    is_kyc_verified_by_admin: 0,
    selfie_image: "",
    is_selfie_uploaded: 0,
    state: "",
    is_mover_setup_profile_done: 0,
    mover_setup_step: 0,
    all_documentation_approved_by_admin: 0,
    unread_notifications: 0,
    unread_alerts: 0,
  },
  moverInfo: {
    acc_verified: 0,
    address: "",
    address_proofs: "",
    card_cvv: "",
    card_expiry: "",
    card_holder_name: "",
    card_number: "",
    card_type: "",
    city: "",
    created_at: "",
    device_token: "",
    device_type: "",
    email: "",
    email_verified_at: "",
    fcm_token: "",
    first_name: "",
    id: 0,
    insurance_copies: "",
    insurance_number: "",
    is_card: 0,
    is_profile_completed: 0,
    is_social: 0,
    is_verified: 0,
    iso: "",
    last_name: "",
    license_copies: "",
    license_number: "",
    new_items: 0,
    new_message: 0,
    otp: "",
    otp_expired_at: "",
    phone_number: "",
    profile_image: "",
    profile_percentage: 0,
    purchase_item: 0,
    push_notification: 0,
    rate: 0,
    social_id: "",
    social_type: "",
    state: "",
    type: "",
    updated_at: "",
    vehicle_type: "",
    total_user_rate: 0,
    avg_rate: 0,
    username: "",
    step: 0,
    customer_id: "",
    latitude: "",
    longitude: "",
    is_blocked_by_admin: 0,
    online: 0,
    stripe_account_id: "",
    apple_secret: "",
    stripe_enabled: 0,
    house_images: "",
    street_address_1: "",
    street_address_2: "",
    country: "",
    zip_code: "",
    kyc_documents: "",
    id_type: null,
    is_kyc_verified_by_admin: 0,
    selfie_image: "",
    is_selfie_uploaded: 0,
    is_mover_setup_profile_done: 0,
    mover_setup_step: 0,
    all_documentation_approved_by_admin: 0,
    unread_notifications: 0,
    unread_alerts: 0,
  },
  errorFromSocial: false,
  address: "",
  notificationCount: 0,
  isNewPackageDelivered: 0,
  moverRequestData: [],
  unread_count: 0,
  unread_alert_count: 0,
};

const settings = createSlice({
  name: "settings",
  initialState,
  reducers: {
    isDarkMode: (
      state: SettingsStateProps,
      { payload }: PayloadAction<boolean>
    ) => {
      state.isDark = payload;
    },
    setUserData: (state, action: PayloadAction<UserData>) => {
      state.userData = action.payload;
    },
    setErrorFromSocial: (state, action: PayloadAction<boolean>) => {
      state.errorFromSocial = action.payload;
    },
    saveAddress: (state, action: PayloadAction<string>) => {
      state.address = action.payload;
    },
    setSaveNotificationCount: (state, action: PayloadAction<number>) => {
      state.notificationCount = action.payload;
    },
    setIsNewPackageDeliverd: (state, action: PayloadAction<number>) => {
      state.isNewPackageDelivered = action.payload;
    },
    setMoverInfo: (state, action: PayloadAction<UserData>) => {
      state.moverInfo = action.payload;
    },
    setMoverRequestList: (state, action: PayloadAction<any[]>) => {
      state.moverRequestData = action.payload;
    },
    setTotalUnreadNotificationCount: (state, action: PayloadAction<number>) => {
      state.unread_count = action.payload;
    },
    setTotalUnreadAlertCount: (state, action: PayloadAction<number>) => {
      state.unread_alert_count = action.payload;
    },
  },
});

export const {
  isDarkMode,
  setUserData,
  setErrorFromSocial,
  saveAddress,
  setSaveNotificationCount,
  setIsNewPackageDeliverd,
  setMoverInfo,
  setMoverRequestList,
  setTotalUnreadNotificationCount,
  setTotalUnreadAlertCount,
} = settings.actions;

export default settings.reducer;
